### ISSUE TITLE
한/일 번역기 추가 및 오류

### ISSUE THREAD

**Issue by jihyeon295** [Yarkana/discord_git#1]
한/일 기능 추가 및 오류(이해안되는 부분인 디스코드 동작부터 고치면 됨) 추가하면 좋은 것들 : 한/일 말고도 한/영도 되게 만드는 부분도 생각해봄 단, 참고한 코드가 글자를 일일이 적는 코딩 방식이라 단어가 적어야 함. 파파고로 돌리는 방식인데 구글도 사용하면 좋을 듯
파일 : translate.js
참고한 깃 허브 : https://github.com/dddieon/discord-bot-ichigomilk.git

**Comment by Yarkana** [comment]
해보니까 입력이 들어오면 그걸 파파고에 넘겨서 번역하고 받아오는 형식임
구식 코드들 수정해서 현재 디스코드에서 실행까지는 되는데
api요청이 잘못됫는지 계속 401:인증실패가 뜸

api에 보내는 요청값 수정해서 받아올 수 있게 하면 됨

DeepL api 같은 경우는 해외카드나 다른 방식이 필요해서 조금 더 연구해볼 예정임

**Comment by Yarkana** [comment]
파파고 번역기 정상작동 끝
DeepL api는 전부다 외국 신용카드 요구해서 못하는 듯함...
